### ISSUE TITLE
PR joselfonseca/laravel-tactician pending

### ISSUE THREAD

**Issue by proyectotau** [proyectotau/TAU#2]
Rollback last commit until PR is merged

https://github.com/joselfonseca/laravel-tactician/pull/11

**Comment by jagarsoft** [comment]
Fixes #2 by 42e43f420cfb4dfe4458b4b3645b3c4753a4470e

**Comment by jagarsoft** [comment]
closes #2

**Comment by proyectotau** [comment]
Fixed #2 by 42e43f420cfb4dfe4458b4b3645b3c4753a4470e
